version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - GIPHY_API_KEY=${GIPHY_API_KEY}

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "3000:80"
    depends_on:
      - backend
