version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - GIPHY_API_KEY=${GIPHY_API_KEY}
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3001:3000" # Host 3001 → Container 3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    depends_on:
      - backend