# docker-compose.yml (base for prod)

version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
    - "5000:5000"
    environment:
    - GIPHY_API_KEY=${GIPHY_API_KEY}
    env_file:
    - .env


  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
